# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_test.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1000, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(870, 720))
        Dialog.setMaximumSize(QtCore.QSize(1360, 720))
        Dialog.setWhatsThis("")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.myView = QtWidgets.QGraphicsView(Dialog)
        self.myView.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myView.sizePolicy().hasHeightForWidth())
        self.myView.setSizePolicy(sizePolicy)
        self.myView.setMinimumSize(QtCore.QSize(800, 400))
        self.myView.setMaximumSize(QtCore.QSize(1100, 600))
        self.myView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.myView.setWhatsThis("")
        self.myView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.myView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.myView.setBackgroundBrush(brush)
        self.myView.setObjectName("myView")
        self.label_CH1 = QtWidgets.QLabel(Dialog)
        self.label_CH1.setGeometry(QtCore.QRect(50, 530, 71, 41))
        self.label_CH1.setWhatsThis("")
        self.label_CH1.setStyleSheet("font: 75 18pt \"Adobe 宋体 Std L\";\n"
"background-color: rgb(255, 255, 0);")
        self.label_CH1.setObjectName("label_CH1")
        self.comboBox_CH1 = QtWidgets.QComboBox(Dialog)
        self.comboBox_CH1.setGeometry(QtCore.QRect(50, 580, 71, 31))
        self.comboBox_CH1.setWhatsThis("")
        self.comboBox_CH1.setObjectName("comboBox_CH1")
        self.comboBox_CH1.addItem("")
        self.comboBox_CH1.addItem("")
        self.spinBox_CH1 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_CH1.setGeometry(QtCore.QRect(90, 670, 51, 31))
        self.spinBox_CH1.setStyleSheet("font: 18pt \"Adobe Arabic\";")
        self.spinBox_CH1.setMinimum(1)
        self.spinBox_CH1.setMaximum(10)
        self.spinBox_CH1.setProperty("value", 2)
        self.spinBox_CH1.setObjectName("spinBox_CH1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 670, 61, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.colorBox_CH1 = QtWidgets.QComboBox(Dialog)
        self.colorBox_CH1.setGeometry(QtCore.QRect(50, 620, 71, 31))
        self.colorBox_CH1.setWhatsThis("")
        self.colorBox_CH1.setObjectName("colorBox_CH1")
        self.colorBox_CH1.addItem("")
        self.colorBox_CH1.addItem("")
        self.colorBox_CH1.addItem("")
        self.colorBox_CH1.addItem("")
        self.colorBox_CH1.addItem("")
        self.colorBox_CH1.addItem("")
        self.comboBox_CH2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_CH2.setGeometry(QtCore.QRect(220, 580, 71, 31))
        self.comboBox_CH2.setWhatsThis("")
        self.comboBox_CH2.setObjectName("comboBox_CH2")
        self.comboBox_CH2.addItem("")
        self.comboBox_CH2.addItem("")
        self.label_CH2 = QtWidgets.QLabel(Dialog)
        self.label_CH2.setGeometry(QtCore.QRect(220, 530, 71, 41))
        self.label_CH2.setWhatsThis("")
        self.label_CH2.setStyleSheet("font: 75 18pt \"Adobe 宋体 Std L\";\n"
"background-color: rgb(0,255,0);")
        self.label_CH2.setObjectName("label_CH2")
        self.colorBox_CH2 = QtWidgets.QComboBox(Dialog)
        self.colorBox_CH2.setGeometry(QtCore.QRect(220, 620, 71, 31))
        self.colorBox_CH2.setWhatsThis("")
        self.colorBox_CH2.setObjectName("colorBox_CH2")
        self.colorBox_CH2.addItem("")
        self.colorBox_CH2.addItem("")
        self.colorBox_CH2.addItem("")
        self.colorBox_CH2.addItem("")
        self.colorBox_CH2.addItem("")
        self.colorBox_CH2.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 670, 61, 31))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.spinBox_CH2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_CH2.setGeometry(QtCore.QRect(260, 670, 51, 31))
        self.spinBox_CH2.setStyleSheet("font: 18pt \"Adobe Arabic\";")
        self.spinBox_CH2.setMinimum(1)
        self.spinBox_CH2.setMaximum(10)
        self.spinBox_CH2.setProperty("value", 2)
        self.spinBox_CH2.setObjectName("spinBox_CH2")
        self.comboBox_CH3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_CH3.setGeometry(QtCore.QRect(380, 580, 71, 31))
        self.comboBox_CH3.setWhatsThis("")
        self.comboBox_CH3.setObjectName("comboBox_CH3")
        self.comboBox_CH3.addItem("")
        self.comboBox_CH3.addItem("")
        self.label_CH3 = QtWidgets.QLabel(Dialog)
        self.label_CH3.setGeometry(QtCore.QRect(380, 530, 71, 41))
        self.label_CH3.setWhatsThis("")
        self.label_CH3.setStyleSheet("font: 75 18pt \"Adobe 宋体 Std L\";\n"
"background-color: rgb(255,255,255);")
        self.label_CH3.setObjectName("label_CH3")
        self.colorBox_CH3 = QtWidgets.QComboBox(Dialog)
        self.colorBox_CH3.setGeometry(QtCore.QRect(380, 620, 71, 31))
        self.colorBox_CH3.setWhatsThis("")
        self.colorBox_CH3.setObjectName("colorBox_CH3")
        self.colorBox_CH3.addItem("")
        self.colorBox_CH3.addItem("")
        self.colorBox_CH3.addItem("")
        self.colorBox_CH3.addItem("")
        self.colorBox_CH3.addItem("")
        self.colorBox_CH3.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(350, 670, 61, 31))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.spinBox_CH3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_CH3.setGeometry(QtCore.QRect(420, 670, 51, 31))
        self.spinBox_CH3.setStyleSheet("font: 18pt \"Adobe Arabic\";")
        self.spinBox_CH3.setMinimum(1)
        self.spinBox_CH3.setMaximum(10)
        self.spinBox_CH3.setProperty("value", 2)
        self.spinBox_CH3.setObjectName("spinBox_CH3")
        self.comboBox_CH4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_CH4.setGeometry(QtCore.QRect(550, 580, 71, 31))
        self.comboBox_CH4.setWhatsThis("")
        self.comboBox_CH4.setObjectName("comboBox_CH4")
        self.comboBox_CH4.addItem("")
        self.comboBox_CH4.addItem("")
        self.label_CH4 = QtWidgets.QLabel(Dialog)
        self.label_CH4.setGeometry(QtCore.QRect(550, 530, 71, 41))
        self.label_CH4.setWhatsThis("")
        self.label_CH4.setStyleSheet("font: 75 18pt \"Adobe 宋体 Std L\";\n"
"background-color: rgb(0,255,255)")
        self.label_CH4.setObjectName("label_CH4")
        self.colorBox_CH4 = QtWidgets.QComboBox(Dialog)
        self.colorBox_CH4.setGeometry(QtCore.QRect(550, 620, 71, 31))
        self.colorBox_CH4.setWhatsThis("")
        self.colorBox_CH4.setObjectName("colorBox_CH4")
        self.colorBox_CH4.addItem("")
        self.colorBox_CH4.addItem("")
        self.colorBox_CH4.addItem("")
        self.colorBox_CH4.addItem("")
        self.colorBox_CH4.addItem("")
        self.colorBox_CH4.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(520, 670, 61, 31))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.spinBox_CH4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_CH4.setGeometry(QtCore.QRect(590, 670, 51, 31))
        self.spinBox_CH4.setStyleSheet("font: 18pt \"Adobe Arabic\";")
        self.spinBox_CH4.setMinimum(1)
        self.spinBox_CH4.setMaximum(10)
        self.spinBox_CH4.setProperty("value", 2)
        self.spinBox_CH4.setObjectName("spinBox_CH4")

        self.retranslateUi(Dialog)
        self.colorBox_CH2.setCurrentIndex(1)
        self.colorBox_CH3.setCurrentIndex(2)
        self.colorBox_CH4.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CH_test"))
        self.label_CH1.setText(_translate("Dialog", " CH1"))
        self.comboBox_CH1.setItemText(0, _translate("Dialog", "开启"))
        self.comboBox_CH1.setItemText(1, _translate("Dialog", "关闭"))
        self.label.setText(_translate("Dialog", "波形宽度"))
        self.colorBox_CH1.setItemText(0, _translate("Dialog", "黄色"))
        self.colorBox_CH1.setItemText(1, _translate("Dialog", "绿色"))
        self.colorBox_CH1.setItemText(2, _translate("Dialog", "白色"))
        self.colorBox_CH1.setItemText(3, _translate("Dialog", "青色"))
        self.colorBox_CH1.setItemText(4, _translate("Dialog", "红色"))
        self.colorBox_CH1.setItemText(5, _translate("Dialog", "紫色"))
        self.comboBox_CH2.setItemText(0, _translate("Dialog", "开启"))
        self.comboBox_CH2.setItemText(1, _translate("Dialog", "关闭"))
        self.label_CH2.setText(_translate("Dialog", " CH2"))
        self.colorBox_CH2.setItemText(0, _translate("Dialog", "黄色"))
        self.colorBox_CH2.setItemText(1, _translate("Dialog", "绿色"))
        self.colorBox_CH2.setItemText(2, _translate("Dialog", "白色"))
        self.colorBox_CH2.setItemText(3, _translate("Dialog", "青色"))
        self.colorBox_CH2.setItemText(4, _translate("Dialog", "红色"))
        self.colorBox_CH2.setItemText(5, _translate("Dialog", "紫色"))
        self.label_2.setText(_translate("Dialog", "波形宽度"))
        self.comboBox_CH3.setItemText(0, _translate("Dialog", "开启"))
        self.comboBox_CH3.setItemText(1, _translate("Dialog", "关闭"))
        self.label_CH3.setText(_translate("Dialog", " CH3"))
        self.colorBox_CH3.setItemText(0, _translate("Dialog", "黄色"))
        self.colorBox_CH3.setItemText(1, _translate("Dialog", "绿色"))
        self.colorBox_CH3.setItemText(2, _translate("Dialog", "白色"))
        self.colorBox_CH3.setItemText(3, _translate("Dialog", "青色"))
        self.colorBox_CH3.setItemText(4, _translate("Dialog", "红色"))
        self.colorBox_CH3.setItemText(5, _translate("Dialog", "紫色"))
        self.label_3.setText(_translate("Dialog", "波形宽度"))
        self.comboBox_CH4.setItemText(0, _translate("Dialog", "开启"))
        self.comboBox_CH4.setItemText(1, _translate("Dialog", "关闭"))
        self.label_CH4.setText(_translate("Dialog", " CH4"))
        self.colorBox_CH4.setItemText(0, _translate("Dialog", "黄色"))
        self.colorBox_CH4.setItemText(1, _translate("Dialog", "绿色"))
        self.colorBox_CH4.setItemText(2, _translate("Dialog", "白色"))
        self.colorBox_CH4.setItemText(3, _translate("Dialog", "青色"))
        self.colorBox_CH4.setItemText(4, _translate("Dialog", "红色"))
        self.colorBox_CH4.setItemText(5, _translate("Dialog", "紫色"))
        self.label_4.setText(_translate("Dialog", "波形宽度"))

